/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeTest_HelloJNI */

#ifndef _Included_NativeTest_HelloJNI
#define _Included_NativeTest_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeTest_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeTest_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
