/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Scalar_ScalarMain */

#ifndef _Included_Scalar_ScalarMain
#define _Included_Scalar_ScalarMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Scalar_ScalarMain
 * Method:    multi01
 * Signature: ([D[D)D
 */
JNIEXPORT jdouble JNICALL Java_Scalar_ScalarMain_multi01
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     Scalar_ScalarMain
 * Method:    multi02
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Scalar_ScalarMain_multi02
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Scalar_ScalarMain
 * Method:    multi03
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Scalar_ScalarMain_multi03
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
